### ISSUE TITLE
CSS issues, all-around

### ISSUE THREAD

**Issue by mandiwise** [redacademy/best-fall-2016#12]
You'll likely get much more specific feedback about this from your design team tomorrow, but I noticed a lot of CSS-related issue (with respect to your site not reflecting the prototypes to the degree of fidelity we would want it to).

There are also some CSS inconsistencies for the same element, but between different pages. Please revisit your CSS, and strive to make it as modular as possible, and also take the time to refine design details throughout the site.

**Comment by annakviese** [comment]
Some of the styles can definitely be reused. Lets sit down on Friday and go through all the pages!

**Comment by annakviese** [comment]
Let's sit down on Monday and go through all the pages the same way we did with UX/UI teams!
