### ISSUE TITLE
Fix images directory

### ISSUE THREAD

**Issue by mandiwise** [redacademy/best-fall-2016#3]
You have an "images" dir and an "Images" dir. I think you are going to have to temporarily move both from your repo, make a commit, and then add the "images" dir back in and make a new commit for that to fix the issue. Git gets weird about uppercase/lowercase letters when changing dir names unfortunately.

Hopefully this also fixes the problem with some of your images 404ing.

**Comment by annakviese** [comment]
Removed the folder , committed, added the folder back and pushed the changes.

**Comment by annakviese** [comment]
Before we deploy on Monday morning ask Mandi to take a look!

**Comment by annakviese** [comment]
fixed
