### ISSUE TITLE
Are default blog posts needed?

### ISSUE THREAD

**Issue by mandiwise** [redacademy/best-fall-2016#9]
If this site does not support default blog posts, please hide them from the WP Admin UI so internal end users don't accidentally add anything here. Also, remove the test blog post you added beforehand if they are not needed.

You can use this as an example to do that:

https://gist.github.com/mandiwise/2ea571ae0773b340af5a

**Comment by macbrett** [comment]
will be added at a later time

**Comment by annakviese** [comment]
not needed for the final presentation but clients will later add this section (the posts from the main blog are showing on the front page)
